language: c

before_script:
  - sudo apt-get update
  - sudo apt-get -y install mono-complete libmono-sqlite4.0-cil

script:
  - xbuild /p:TargetFrameworkProfile="" /p:Configuration=Release

env:
  - secure: "NFfeQJbA3rVU+mbG8ljXq3USaw2RU4/AffWSPvm6TiSfXoBiELDz6fT08+jD8MIkjbBEvJYYu20yG7vJaqxCnO/P3WAsQaR3nwDeTbsJ6Hu7604iaTKKj+C7+ER7hMFb0d7ETeiQdLLNP+JxRWnCVK01ct6bcpRBUPYZGyQqicA="

deploy:
  provider: releases
  skip_cleanup: true
  api-key: $KEY
  on:
    all_branches: true
    tags: true
  file:
    - "YGOCore/bin/Release/OcgWrapper.dll"
    - "YGOCore/bin/Release/YGOServer.exe"
